
const FETCH_DATA_CART = 'FETCH_DATA_CART';
const ADD_TO_CART = 'ADD_TO_CART';
const CHANGE_QUANTITY = 'CHANGE_QUANTITY';
const DELETE_PRODUCT = 'DELETE_PRODUCT';
const RESET_CART = 'RESET_CART';

export { FETCH_DATA_CART, ADD_TO_CART, CHANGE_QUANTITY, DELETE_PRODUCT, RESET_CART}